version: '3.8'
services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=lesson-1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: flyway/flyway
    command:
      -url=jdbc:postgresql://postgres:5432/lesson-1 -schemas=public -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - postgres